import { Section, SectionHeading } from "@/components/site/section";
import { StatStrip } from "@/components/site/stat-strip";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ablation, corpusStats, engineMetrics } from "@/lib/content";
import { cn } from "@/lib/utils";

export function MetricsSection() {
  return (
    <Section id="results">
      <SectionHeading
        eyebrow="Results"
        title="Regenerated by script,"
        accent="never typed by hand."
        lead="Two precision mechanisms, measured independently over 155 genuine samples. Precision normally trades against recall. Here it did not."
      />

      <StatStrip stats={corpusStats.slice(0, 3)} columns={3} className="mt-12" />

      <div className="mt-14 grid gap-10 lg:grid-cols-2 lg:gap-14">
        <div>
          <h3 className="mono-label text-foreground/45">Engine — 46 fixtures, four classes</h3>
          <div className="mt-5 overflow-hidden rounded-xl border border-border bg-card">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[52%]">Metric</TableHead>
                  <TableHead className="text-right">Result</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {engineMetrics.map((row) => (
                  <TableRow key={row.metric}>
                    <TableCell className="align-top">
                      <span className="text-[0.9375rem]">{row.metric}</span>
                      {row.note ? (
                        <span className="mt-1 block font-serif text-xs text-foreground/45 italic">
                          {row.note}
                        </span>
                      ) : null}
                    </TableCell>
                    <TableCell className="text-right align-top font-mono text-[0.9375rem] font-medium">
                      {row.result}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>

        <div>
          <h3 className="mono-label text-foreground/45">
            The ablation — 155 genuine samples
          </h3>
          <div className="mt-5 overflow-hidden rounded-xl border border-border bg-card">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Configuration</TableHead>
                  <TableHead className="text-right">FP rate</TableHead>
                  <TableHead className="text-right">Fraud recall</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {ablation.map((row) => (
                  <TableRow key={row.configuration} className={cn(row.shipped && "bg-primary/6")}>
                    <TableCell className="text-[0.9375rem]">
                      {row.configuration}
                      {row.shipped ? (
                        <Badge
                          variant="outline"
                          className="ml-2 border-primary/40 text-[0.625rem] text-primary"
                        >
                          shipped
                        </Badge>
                      ) : null}
                    </TableCell>
                    <TableCell className="text-right font-mono text-[0.9375rem]">
                      {row.fpRate}
                    </TableCell>
                    <TableCell className="text-right font-mono text-[0.9375rem]">
                      {row.fraudRecall}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <p className="copy mt-6">
            95% recall in every configuration. And every false positive under rules alone came
            from the adversarial set — none from the other 120 samples. Investor-awareness copy is
            exactly where keyword systems fail.
          </p>
        </div>
      </div>
    </Section>
  );
}
